### PR TITLE
ARIA-437: ARIA does not support some of the combinations for requirement declarations (at the node type) and some for requirement assignments (at the node template)

### PR DESCRIPTION
**Pull request by VenkatesanVenugopal**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by VenkatesanVenugopal** [comment]
Hi Team,

Can any one review my patch and provide the comments if any.

Regards,
Venkatesan V

**Comment by VenkatesanVenugopal** [comment]
Thanks for the comments. Let me incorporate the comments and have a separate pull request later.

**Comment by tnadeauaria** [comment]
Were we going to discuss the PR this morning?

BTW I see you withdrew the earlier one. When are you planning to push the
updated?

--Tom

**Pull request closed without merging**
