### PR TITLE
ARIA-118 plugin.yaml importing

### PR DESCRIPTION
**Pull request by djay87**
This commit supports using the plugin.yaml present in a plugin wagon archive in a more simpler way as described below.

imports:

    - file: <plugin_name>-<plugin_version>
       repository: plugins

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by djay87** [comment]
Can anyone of the admin review this PR ?

**Comment by djay87** [comment]
Kindly review this PR, so that i can contribute for another story.

**Comment by tnadeauaria** [comment]
Multiple changes were requested after a 1:1 code review.  DJ agreed to implement the changes and push a new PR.

**Pull request closed without merging**
