### PR TITLE
ARIA-277 Support for Type Qualified Name

### PR DESCRIPTION
**Pull request by djay87**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by djay87** [comment]
Could you please check if all my commits are squashed now ? Am bit new to this squash concept.

**Comment by mxmrlv** [comment]
Yeah, no problem. Basically as long as github says this PR has 9 commits, the commits were not fully squashed. you can find a quick answer to how to squash [here](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git), but please be careful, i would copy the working dir for the forked repo and try squashing from that copy (only when you are 100% sure all of your changes are present in the single commit, you should push back to your branch).

**Comment by djay87** [comment]
Hi Max,

Finally i was able to squash all the commits and resolve the merge issue with a single commit. Kindly check and let me know if its fine this time :)

**Comment by mxmrlv** [comment]
looks good :smiley: will merge into master shortly

**Comment by mxmrlv** [comment]
This PR was merged to master, can you please erase the PR?

**Comment by djay87** [comment]
Thanks max. I hope erasing the PR means closing this PR ?

**Pull request closed without merging**
